# Generated by Django 2.1 on 2018-11-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
