# Generated by Django 2.1 on 2018-11-16 18:36

from django.db import migrations
import django.utils.timezone
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=places.fields.PlacesField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
