# Generated by Django 2.1 on 2018-11-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0002_auto_20181120_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
    ]
