# Generated by Django 2.1 on 2018-11-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0002_auto_20181118_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_also_volunteer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
