# Generated by Django 2.1 on 2018-11-19 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0003_user_is_also_volunteer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='limit',
        ),
        migrations.AddField(
            model_name='post',
            name='timelimit',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
