# Generated by Django 2.1 on 2018-11-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0004_auto_20181120_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
    ]
