# Generated by Django 2.1 on 2018-11-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0004_auto_20181119_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active_post',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
