# Generated by Django 2.1 on 2018-11-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0006_auto_20181120_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='requested',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='served',
            field=models.IntegerField(default=0),
        ),
    ]
