# Generated by Django 2.1 on 2018-11-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0007_auto_20181121_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assisted',
            field=models.IntegerField(default=0),
        ),
    ]
