# Generated by Django 2.1 on 2018-11-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0009_auto_20181121_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='active_post',
            field=models.BooleanField(default=True),
        ),
    ]
