# Generated by Django 2.1 on 2018-11-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0010_auto_20181121_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reported',
            field=models.ManyToManyField(blank=True, related_name='reported', to='happiness.post'),
        ),
    ]
