# Generated by Django 2.1 on 2018-11-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0013_auto_20181122_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='datelim',
            field=models.DateField(default='2018-11-11'),
        ),
        migrations.AddField(
            model_name='post',
            name='timelim',
            field=models.TimeField(default='08:34:20'),
        ),
        migrations.AlterField(
            model_name='post',
            name='timelimit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
