# Generated by Django 2.1 on 2018-11-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0019_auto_20181124_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='adress',
            field=models.TextField(blank=True),
        ),
    ]
