# Generated by Django 2.1 on 2018-11-24 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0020_post_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='adress',
            new_name='address',
        ),
    ]
